version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules   # giữ node_modules trong container, không bị ghi đè
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true   # cần cho Vite khi chạy trong Docker trên Win/Mac
